"""added requests

Revision ID: 672f0f69d66f
Revises: 0c0f69622a10
Create Date: 2020-09-17 12:50:39.300278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672f0f69d66f'
down_revision = '0c0f69622a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###
